[workspace]
resolver = "2"
members = ["icli_derive"]

[workspace.package]
license = "MIT"
edition = "2021"

[package]
name = "icli"
version = "0.1.0"
description = "`icli` is a personal command-line tool, which includes various commonly used utilities."
repository = "https://github.com/druagoon/icli-rs"
edition.workspace = true
license.workspace = true
categories = ["command-line-interface"]
keywords = ["icli", "cli"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive", "env", "cargo"] }
clap_complete = "4.5.2"
pnet = "0.34.0"
icli_derive = { path = "./icli_derive" }
