allow-branch = ["master"]
pre-release-hook = [
    "git",
    "cliff",
    "-o",
    "CHANGELOG.md",
    "--tag",
    "v{{version}}",
]
publish = false
consolidate-commits = false
pre-release-commit-message = "chore: Release {{crate_name}} {{version}}"
