[proxy]
# all = "http://127.0.0.1:7890"
# http = "http://127.0.0.1:7890"
# https = "http://127.0.0.1:7890"

[clash]
# user_agent = "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

[[clash.proxy.providers]]
# primary = true
# name = ""
# url = ""
# interval = 172800

[clash.app.clashx]
# config_dir = "~/.config/clash"

[clash.app.clash_verge]
# config_dir = ""

[quantumultx.remote.server]
# tag = ""
# url = ""
# img_url = ""
# interval = 86400

[quantumultx.mitm]
# passphrase = ""
# p12 = ""
